services:
  web:
    build: .
    container_name: tutorias_web
    ports:
      - "8095:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=tutorias_db

  mysql:
    image: mysql:8.0
    container_name: tutorias_mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorias_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    container_name: tutorias_adminer
    ports:
      - "8096:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: